"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type TeamInvite = { team: { name: string; shortName: string; logoUrl?: string | null }; playerCount: number; spaces: number; error?: string };
export function JoinTeam() {
  const [invite, setInvite] = useState<TeamInvite | null>(null); const [message, setMessage] = useState(""); const [done, setDone] = useState(false); const [photoName, setPhotoName] = useState("");
  const code = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("code") ?? "";
  useEffect(() => { void fetch(`/api/join?code=${encodeURIComponent(code)}`).then(async (response) => { const body = await response.json(); setInvite(body); if (!response.ok) setMessage(body.error); }); }, [code]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); form.set("code", code); const response = await fetch("/api/join", { method: "POST", body: form }); const body = await response.json(); setMessage(response.ok ? `Welcome to ${body.team.name}. Your profile has been saved to the team.` : body.error); if (response.ok) setDone(true); }
  return <main className="join-page"><section className="join-card"><div className="join-brand"><span>C</span><b>CORE CRICKET</b></div>{!invite && !message ? <p>Opening your team invitation…</p> : invite?.team ? <><div className="join-team-head">{invite.team.logoUrl ? <img src={invite.team.logoUrl} alt="" /> : <i>{invite.team.shortName.slice(0,1)}</i>}<div><span>YOU HAVE BEEN INVITED TO</span><h1>{invite.team.name}</h1><p>{invite.spaces} of 16 roster places available</p></div></div>{done ? <div className="join-success">✓<h2>Profile created</h2><p>{message}</p><Link href="/">Open Core Cricket</Link></div> : <form onSubmit={submit}><label>Full name<input name="name" required placeholder="Your full name" /></label><label>Profile picture<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => setPhotoName(event.target.files?.[0]?.name ?? "")} /><small>{photoName || "Browse your phone and select a picture (maximum 5 MB)."}</small></label><label>Player role<select name="role"><option>All-rounder</option><option>Batter</option><option>Fast bowler</option><option>Spin bowler</option><option>Wicketkeeper</option></select></label><div><label>Batting style<select name="battingStyle"><option>Right hand</option><option>Left hand</option></select></label><label>Bowling style<select name="bowlingStyle"><option>Right-arm medium</option><option>Right-arm fast</option><option>Left-arm pace</option><option>Off spin</option><option>Leg spin</option><option>Does not bowl</option></select></label></div><label>Short profile<input name="profileBio" placeholder="Playing history or a short bio" /></label>{message && <p className="join-error">{message}</p>}<button type="submit">Create profile and save picture</button><small>Your picture saves automatically. You can change or remove it later from your profile.</small></form>}</> : <div className="join-success"><h2>Invitation unavailable</h2><p>{message}</p></div>}</section></main>;
}
